# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build' # Optional
      cmakeArgs: ".."
  - script: make
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/allodummy*
        build/*.so
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Linux-x64
- job: Mac
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build' # Optional
      cmakeArgs: "-G \"Unix Makefiles\" .."
  - script: make
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/allodummy*
        build/*.dylib
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Mac-x64
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CMake@1
    inputs:
      workingDirectory: 'build' # Optional
      cmakeArgs: ".."
  - task: VSBuild@1
    displayName: "Visual Studio build"
    inputs:
      msbuildArchitecture: 'x64'
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/**/allo*.exe
        build/**/allo*.dll
        build/**/allo*.lib
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Windows-x64
