# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: sudo sh install-cmake.sh
    displayName: 'Install CMake'
  - script: sudo apt-get install nasm
    displayName: 'Install nasm'
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: ".."
  - script: env VERBOSE=1 make allonet
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/allodummy*
        build/*.so
        lang/**/*.lua
        lang/**/README.md
      targetFolder: $(Build.ArtifactStagingDirectory)/version
  - script: bash adjust-staging-dir.sh $(Build.ArtifactStagingDirectory) linux-x64
    displayName: "Adjust staging directory"
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-ci'
      regionName: 'eu-north-1'
      bucketName: 'alloverse-downloads-prod'
      targetFolder: 'allonet'
      filesAcl: 'public-read'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Linux-x64


- job: Mac
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: brew install nasm
    displayName: 'Install nasm'
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "-G \"Unix Makefiles\" \"-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64\" .."
  - script: make allonet
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/allodummy*
        build/*.dylib
        lang/**/*.lua
        lang/**/README.md
      targetFolder: $(Build.ArtifactStagingDirectory)/version
  - script: bash adjust-staging-dir.sh $(Build.ArtifactStagingDirectory) mac-universal
    displayName: "Adjust staging directory"
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-ci'
      regionName: 'eu-north-1'
      bucketName: 'alloverse-downloads-prod'
      targetFolder: 'allonet'
      filesAcl: 'public-read'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Mac-x64


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      git config --global --add filter.lfs.required true
      git config --global --add filter.lfs.smudge "git-lfs smudge -- %f"
      git config --global --add filter.lfs.process "git-lfs filter-process"
      git config --global --add filter.lfs.clean "git-lfs clean -- %f"
    displayName: Configure LFS for use with submodules
  - checkout: self
    lfs: true
    submodules: true
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "-A x64 .."
  - task: VSBuild@1
    displayName: "Visual Studio build"
    inputs:
      solution: 'build/allonet.vcxproj'
      configuration: 'release'
      msbuildArchitecture: 'x64'
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/**/allo*.exe
        build/**/allo*.dll
        build/**/allo*.lib
        build/**/allo*.pdb
        lang/**/*.lua
        lang/**/README.md
      targetFolder: $(Build.ArtifactStagingDirectory)/version
  - script: bash adjust-staging-dir.sh $(Build.ArtifactStagingDirectory) windows-x64
    displayName: "Adjust staging directory"
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-ci'
      regionName: 'eu-north-1'
      bucketName: 'alloverse-downloads-prod'
      targetFolder: 'allonet'
      filesAcl: 'public-read'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Windows-x64


- job: Android
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      git config --global --add filter.lfs.required true
      git config --global --add filter.lfs.smudge "git-lfs smudge -- %f"
      git config --global --add filter.lfs.process "git-lfs filter-process"
      git config --global --add filter.lfs.clean "git-lfs clean -- %f"
    displayName: Configure LFS for use with submodules
  - checkout: self
    lfs: true
    submodules: true
  - script: brew install nasm
    displayName: 'Install nasm'
  - task: CMake@1
    inputs:
      workingDirectory: 'build'
      cmakeArgs: "cmake -DCMAKE_TOOLCHAIN_FILE=~/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a .."
  - script: make allonet
    workingDirectory: build
    displayName: "Make"
  - task: CopyFiles@2
    displayName: "Stage artifacts"
    inputs:
      contents: |
        include/**/*.h
        build/*.so
        lang/**/*.lua
        lang/**/README.md
      targetFolder: $(Build.ArtifactStagingDirectory)/version
  - script: bash adjust-staging-dir.sh $(Build.ArtifactStagingDirectory) android-x64
    displayName: "Adjust staging directory"
  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws-ci'
      regionName: 'eu-north-1'
      bucketName: 'alloverse-downloads-prod'
      targetFolder: 'allonet'
      filesAcl: 'public-read'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: Allonet-Android
